### ISSUE TITLE
FYI: Added to org-almanac

### ISSUE THREAD

**Issue by alphapapa** [tgbugs/orgstrap#2]
Hi,

I confess that I don't fully understand Orgstrap, but having done some similar things with using Org files as somewhat-self-contained applications (e.g. [fitness.org](https://www.reddit.com/r/emacs/comments/a4zipp/fitnessorg_an_emacs_foodweightworkout_tracker/)) it's very interesting.

So, FYI, I added it to org-almanac in a new section: https://alphapapa.github.io/org-almanac/#Software  Let me know what you think.  :)

**Comment by tgbugs** [comment]
Thanks! I think you nailed it in terms of understanding.

I have a number of org files in the works that feel like stand-alone applications and that are more accessible to non-Emacs users (e.g. clickable buttons via creative use of org-link, configure Emacs to use CUA, configure the mouse to open and close headings). Once those are visible I will add a section of examples.

It is probably ok to leave out the `This file bootstraps itself to provide the functionality needed to use orgstrap in any Org file.` line since it only applies inside the readme itself.

**Comment by alphapapa** [comment]
Thanks, I'll remove that part.
