### ISSUE TITLE
FYI: org-make-toc

### ISSUE THREAD

**Issue by alphapapa** [tgbugs/orgstrap#3]
BTW, the readme is very thorough, but it feels a bit hard to navigate.  May I recommend using https://github.com/alphapapa/org-make-toc ?  You can see how I use it in some of my projects to generate multiple tables of contents at different levels to make navigation much easier.  For example:

* https://github.com/alphapapa/org-almanac/blob/master/almanac.org
* https://alphapapa.github.io/org-almanac/
* https://github.com/alphapapa/org-ql

**Comment by tgbugs** [comment]
Thanks for the feedback, and I agree. I looked into trying to use org-make-toc, but couldn't quite get it to work from the example I was following at the time (iirc the nyxt documentation) so I put it on the back burner. Your examples here definitely help.

**Comment by alphapapa** [comment]
A comprehensive example is linked in the readme: https://github.com/alphapapa/org-make-toc/blob/master/example.org

**Comment by tgbugs** [comment]
Ah, I remember why this was an issue now. There is something that I have in my config that causes
`line-move: End of buffer` errors (that I cannot trap) whenever I try to run `org-make-toc` on any org file.
Running with `emacs -q` makes it possible to build the toc, but since it breaks my workflow and I have
not had time to hunt down the underlying issue, I have not pursued it.

edit: one additional note for the record. The fact that I have to add custom ids to all the headings so that
html export isn't broken by default is an additional level of friction (even thought `broken-links:t` is available,
I often do not want to use it since it opens everything up to link-rot).

**Comment by alphapapa** [comment]
> Ah, I remember why this was an issue now. There is something that I have in my config that causes
> `line-move: End of buffer` errors (that I cannot trap) whenever I try to run `org-make-toc` on any org file.
> Running with `emacs -q` makes it possible to build the toc, but since it breaks my workflow and I have
> not had time to hunt down the underlying issue, I have not pursued it.

That's strange.  Please let me know if you find out what's causing that.

> 
> edit: one additional note for the record. The fact that I have to add custom ids to all the headings so that
> html export isn't broken by default is an additional level of friction (even thought `broken-links:t` is available,
> I often do not want to use it since it opens everything up to link-rot).

I'm not sure exactly what you mean.  Have you seen this option?

https://github.com/alphapapa/org-make-toc/blob/26fbd6a7e1e7f8e473fe3a5f74faec715c3a05aa/org-make-toc.el#L154

As well, you may find this helpful: https://github.com/alphapapa/unpackaged.el#export-to-html-with-useful-anchors

**Comment by tgbugs** [comment]
> That's strange. Please let me know if you find out what's causing that.

Turns out that this was related to another long standing issue I was having with some export backends and the concurrence of the two was what let me finally solve the issue. It was completely unrelated to org-make-toc (one of my custom syntax propertization functions called next-logical-line in a way that it could fail, and somehow a failure during propertization broke html export, odt export, and org-make-toc, I have no idea why, but that is an adventure for another day). So many thanks for this issue because it finally pointed me in the right direction to solve that bug.

> I'm not sure exactly what you mean. Have you seen this option?

I'm mostly just complaining about the number of headlines I have :). I think what I need is a function that automatically adds a github formatted CUSTOM_ID property to all headlines (or perhaps just those included in the TOC).

**Comment by tgbugs** [comment]
Alright, I added a TOC. Still a bit long, but at least easier to navigate on github until I can figure out a better structure. Closing since I have the workflow in place. Thanks!
